openapi: 3.0.0
info:
  title: '生活港小程序API文档'
  version: 1.0.0
paths:
  /addressadmin/create:
    post:
      tags:
        - address
      summary: 添加地址
      requestBody:
        description: 添加地址时所需传的数据
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - name
                - cellphone
                - province_id
                - city_id
                - county_id
                - detailed_address
              properties:
                name:
                  description: 收件人姓名
                  type: string
                cellphone:
                  description: 收件人电话
                  type: string
                province_id:
                  description: 省ID
                  type: integer
                city_id:
                  description: 市ID
                  type: integer
                county_id:
                  description: 区ID
                  type: integer
                detailed_address:
                  description: 详细地址
                  type: string
              type: object
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 正确返回时为0, type: integer }
                  message: { description: 信息描述, type: string }
                  data: { description: 返回数据体, properties: { create_result: { description: 创建结果是否成功, type: boolean }, id: { description: 新增的地址ID, type: integer } }, type: object }
                type: object
  /addressadmin/update:
    post:
      tags:
        - address
      summary: 更新地址
      requestBody:
        description: 更新地址时所需传的数据
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - id
                - name
                - cellphone
                - province_id
                - city_id
                - county_id
                - detailed_address
              properties:
                id:
                  description: 地址ID
                  type: integer
                name:
                  description: 收件人姓名
                  type: string
                cellphone:
                  description: 收件人电话
                  type: string
                province_id:
                  description: 省ID
                  type: integer
                city_id:
                  description: 市ID
                  type: integer
                county_id:
                  description: 区ID
                  type: integer
                detailed_address:
                  description: 详细地址
                  type: string
              type: object
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 正确返回时为0, type: integer }
                  message: { description: 信息描述, type: string }
                  data: { description: 返回数据体, properties: { update_result: { description: 更新结果是否成功, type: boolean }, id: { description: 更新后的新地址ID, type: integer } }, type: object }
                type: object
  /addressadmin/delete:
    post:
      tags:
        - address
      summary: 删除地址
      requestBody:
        description: 更新地址时所需传的数据
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - id
              properties:
                id:
                  description: 地址ID
                  type: integer
              type: object
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 正确返回时为0, type: integer }
                  message: { description: 信息描述, type: string }
                  data: { description: 返回数据体, properties: { delete_result: { description: 删除结果是否成功, type: boolean } }, type: object }
                type: object
  /address/provinceList:
    get:
      tags:
        - address
      summary: 省份-列表
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 正确返回时为0, type: integer }
                  message: { description: 信息描述, type: string }
                  data: { description: 返回数据体, properties: { province_list: { description: 省份列表, type: array, items: { description: 省份具体参数值, properties: { id: { description: 省id, type: string }, name: { description: 省份名称, type: string }, pid: { description: 省的父级id, type: string }, province_id: { description: 省id, type: string } }, type: object } } }, type: object }
                type: object
  /address/cityList:
    get:
      tags:
        - address
      summary: 市-列表
      parameters:
        -
          name: id
          in: query
          description: 省份id
          required: true
          schema:
            type: integer
            default: '110000'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 正确返回时为0, type: integer }
                  message: { description: 信息描述, type: string }
                  data: { description: 返回数据体, properties: { province_list: { description: 省份列表, type: array, items: { description: 省份具体参数值, properties: { id: { description: 市id, type: string }, name: { description: 市名称, type: string }, pid: { description: 市的父级id, type: string }, city_id: { description: 市id, type: string } }, type: object } } }, type: object }
                type: object
